# HTTP Server
server:
  port: 8888

spring:
  application:
    name: configserver 

---
spring:
  cloud:
    config:
      server:
        git:
          uri:  ${GITREPOLOCATION}
          default-label: master
  profiles:
    active: dev